name: Usage Report

on:
  schedule:
    - cron: "3 9 * * *"  # Runs at 9:03 AM every day (UK Time)
  workflow_dispatch:  # Allows manual triggering

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
        sudo apt-get install -y wget curl
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        wget -N https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        python -m pip install --upgrade pip
        pip install requests python-dotenv selenium

    - name: Run Usage Report Script with xvfb
      env:
        PHANTOMBUSTER_API_KEY: ${{ secrets.PHANTOMBUSTER_API_KEY }}
        MAKE_API_KEY: ${{ secrets.MAKE_API_KEY }}
        MAKE_ORG_ID: ${{ secrets.MAKE_ORG_ID }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        ZAPIER_EMAIL: ${{ secrets.ZAPIER_EMAIL }}
        ZAPIER_PASSWORD: ${{ secrets.ZAPIER_PASSWORD }}
      run: |
        xvfb-run -a python usage.py
