name: Usage Report

on:
  schedule:
    - cron: "3 9 * * *"  # Runs at 9:03 AM every day (UK Time)

  workflow_dispatch:  # Allows manual triggering

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Usage Report Script
      env:
        PHANTOMBUSTER_API_KEY: ${{ secrets.PHANTOMBUSTER_API_KEY }}
        MAKE_API_KEY: ${{ secrets.MAKE_API_KEY }}
        MAKE_ORG_ID: ${{ secrets.MAKE_ORG_ID }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        python usage.py
